### ISSUE TITLE
Update the civity provided CKAN scheme for DCAT-AP to support "mandatory fields" from the dcat spec.

### ISSUE THREAD

**Issue by hcvdwerf** [GenomicDataInfrastructure/gdi-userportal-ckanext-dcat#6]
As a catalog owner, I want to harvest/show all official DCAT-AP fields in the catalog. Therefore, there needs to be a mapping between all fields from the DCAT-AP specification and our CKAN scheme. Currently, CKAN only supports DCAT-AP 2.1.

Acceptance criteria:

- Scheming made for all DCAT-AP 3.0 fields
- Scheming tested in Civity CKAN catalog

**Comment by brunopacheco1** [comment]
I will close this story in favor of https://github.com/GenomicDataInfrastructure/gdi-userportal-ckanext-gdi-userportal/issues/11 , where the scheme file is.
